### ISSUE TITLE
metrics calculation on some frames without foreground pixels

### ISSUE THREAD

**Issue by james20141606** [valeoai/MVRSS#1]
Hi, I have a question about the calculation of some metrics including IoU, DICE, precision, and recall. In your codes I think you add all frames' confusion matrix together to have the metrics you want. But I found that the dataset contains some frames without any foreground pixels, for example:

<img width="501" alt="Screen Shot 2021-07-16 at 9 53 27 PM" src="https://user-images.githubusercontent.com/14315324/126021839-59fc29ff-68b3-43e6-9807-7051e68d5228.png">

The frame without foreground pixel will give a 0 value for the above metrics. So I am afraid the performance of the model is actually underestimated. I wonder if it is more reasonable to exclude frames without the foreground pixel?

**Comment by ArthurOuaknine** [comment]
Hi, I apologise for the late reply. This a relevant remark.
We have chosen to consider the "background" as a class in its own right because it contains a lot of information: speckle noise, clutters, zero Doppler noise an so on. The model must therefore recognise it in the same way as the other classes and thus distinguish noise signatures from the object signatures.
We chose to keep the background to compute our metrics (even if there is only background) to quantify if a method confuses noise and the objects.
Performances on the background are between 98% and 99.9%, but we believe it is informative about the behaviour of the considered models.

It might be interesting to quantitatively evaluate the models without the background as you asked. The scores will indeed be lower, but some information will be missing and this does not change the predictions of the model. 
Another evaluation hint you could explore is to evaluate the performances using an harmornic mean instead of a arithmetic mean as we have done. This will highlight poor performance on specific classes and can be adapted.

I hope this helps. Please let me know if you are considering exploring new evaluation methods.
